### ISSUE TITLE
beginner question: how can I use haskell in lua?

### ISSUE THREAD

**Issue by molleweide** [hslua/hslua#105]
Hello there,

I am a music producer and I am used to scripting with lua in my digital audio workstation.
If I would like to try out haskell for doing midi processing how can I access haskell from my lua scripts? I have looked at some of the example files provided but this is still a mystery to me. I think that I am kind of understanding how lua is accessed from haskell but I don't understand the other way around. I am a beginner with haskell but I thought that a good way of hammering haskell into my life would be to try to use it in music production because then I can come up with good practical situations to use it in.
Can somebody please show me the minimal stuff one needs to do in order to use haskell in lua? I use the Cockos Reaper DAW which uses lua 5.3 so I do believe that this should work. It could be quite cool and I have become quite blown away by how one starts to think differently when using haskell.

Also if someone has the time to show me this then maybe this could be added to the examples directory also.

Cheers,

**Comment by tarleb** [comment]
Hi @molleweide, thanks for asking. I'm not sure if I can explain this well without knowing some details about kind of packages you currently use, and how you plan to bring in HsLua.

Here are some rules of thumb:
  - the easiest is to write a Haskell program which can then be extended via Lua. This is were HsLua shines (in my *very* biased opinion).
  - the other direction, writing Lua and extending it with a Lua package written in Haskell, is still possible, but not beginner friendly: it requires some dabbling with the compiler, and probably some additional C code.
  - the Haskell-Lua bridge is reasonably fast, but if you have low-latency requirements, the garbage collectors of both languages could make that difficult.

I'll try to add an example for a Lua module written in Haskell to the hslua-examples.

**Comment by molleweide** [comment]
Yo thank you very much for replying to my question. I realize based on your answer that my
question was very unclear but it might be that your reply was the perfect reply to me because
this has forced me to think more about what I actually want to do.

To answer your first question I am not sure what to answer on what packages I am using but my environment looks
like this:

I am using a lua framework for my music program that turns it into a vim-like music editor where everything is
scripted in lua and I can add new lua script functions on the fly. The Cockos Reaper DAW has lua embedded so
everything can be scripted with lua, and with the vim-framework each pressable character is mapped to a lua function
and so now we have a nice way of controlling the daw purely from code.

My idea has been to brute force haskell into my music production somehow. I am thinking that maybe
if I highlight midi notes I would like to appli some kind of transformation or create rhyhtmic or harmonic patterns
and I think this is where haskell should come in. But now that I am writing this I am realizing that maybe
I should instead have a standalone haskell file that I pass my data to and then pass/recieve data to/from
this haskell program. Would this make more senser?

At first I thought that what I need is to be able to write or "script" haskell into my lua files but maybe
that is not the smartest way to do it. If the most convenient way is to use a standalone haskell program then maybe
hslua might be overkill for me.

I would also like to do algorhitmic style composition with haskell but I do believe that here as well the
best method might be to pass my start data to a haskell program and then return the data into my midi files
in reaper so that everything is captured or recorded.

Anyways thanks for replying because now I think I know more clearly what to do.

**Comment by molleweide** [comment]
Hey, is `os.execute()` the most appropriate function to use when interfacing with a haskell program?

**Comment by tarleb** [comment]
I think that's a good plan and should work well :+1:

**Comment by molleweide** [comment]
nice thanks!
