### ISSUE TITLE
Create `TypedField` for modules

### ISSUE THREAD

**Issue by sondr3** [hslua/hslua#128]
Quick feature request, I really enjoy working with `hslua`, so thanks a lot for the maintenance and stewardship over it 😃 

I was wondering if it would be useful to have a typed field kind, similar to how functions have parameters with descriptions, types and so on. Right now I have resorted to adding this to the documentation string, but it'd be nice to have them in the type themselves. I'm writing a renderer to be used with [lua-language-server annotations](https://github.com/sumneko/lua-language-server/wiki/Annotations) to give automatic typings and autocompletion for HsLua modules.

**Comment by tarleb** [comment]
I don't even remember why I didn't add that in the first place. This should definitely be part of the next release.

Your project sounds interesting, is there some way that I could learn more about it? This would be immensely useful for projects like @quarto-dev that build heavily on code written with hslua.

**Comment by sondr3** [comment]
I might have a prototype ready over the Christmas holidays, but it is essentially what the now deprecated `HsLua.Packaging.Rendering` was for Markdown but for LSP annotations instead.

**Comment by tarleb** [comment]
I finally have time to work on hslua again. It might be a few more weeks before I can do a full release though.
