### ISSUE TITLE
Is there a way to restrict access rights of code execution?

### ISSUE THREAD

**Issue by ad-si** [hslua/hslua#143]
I'm looking for something like Deno's permission management (https://docs.deno.com/runtime/manual/basics/permissions) to restrict the rights of the executed code to access files, network, ….
Is that possible?

**Comment by tarleb** [comment]
We've been considering doing something like that, but it's not on my roadmap for now.

**Comment by ad-si** [comment]
Ok, thanks for the heads up!
Did you think about any implementation details already? I might actually give this a shot to implement myself and any pointers would be great!

BTW: There is a fairly new option to close such issues with "Close as not planned". Just click on the arrow next to the "Close issue" button to see it.

**Comment by ad-si** [comment]
Ah, I would have thought that Haskell sets the limits for the Lua execution, but Lua itself enforcing them makes more sense I guess.
