### ISSUE TITLE
How to get more information out of a backtrace?

### ISSUE THREAD

**Issue by tchoutri** [hslua/hslua#148]
My [project](https://github.com/tchoutri/confer) has grown a bit and I intend to provide Lua APIs implemented in Haskell or in Lua.

I have created a couple of modules, like [confer.lua](https://github.com/tchoutri/confer/blob/main/runtime/lua/confer.lua) (which is native Lua) or [user](https://github.com/tchoutri/confer/blob/main/src/Confer/API/User.hs) which is implemented in Haskell.

I previously had made the `confer` API global (`setglobal`), but I think I want to favour explicit imports (which play nicer with LuaLS, since the identifiers are defined).

My [Evaluator](https://github.com/tchoutri/confer/blob/main/src/Confer/Config/Evaluator.hs) now looks like this:

```haskell
    Lua.openlibs -- load the default Lua packages
    Lua.dofile (Just "./runtime/lua/confer.lua")
    Lua.registerModule Lua.System.documentedModule
    Lua.registerModule userModule
    Lua.registerModule hostModule
    Lua.dofile (Just "./doc/confer_example.lua")
    Lua.resultToEither <$> Lua.runPeeker peekConfig Lua.top
```

And I try to evaluate [this file](https://github.com/tchoutri/confer/blob/main/runtime/lua/confer.lua)

But I get this exception:

```
confer: table expected, got string
	while retrieving list
	while retrieving config
```

I thought I had put enough `Lua.retrieving`s in the peekers, but apparently there's a problem somewhere.

My question is actually if there's a way to make the error more verbose. Or maybe it's a pattern you already know?

**Comment by tchoutri** [comment]
You can reproduce by running `cabal run confer -- check` in the repository.

**Comment by tarleb** [comment]
One more thing: `peekFieldRaw` uses `retrieving` internally, so no need for an extra wrapper.

**Comment by tchoutri** [comment]
Super useful! Indeed this gives me a much better error:

```
confer: Lua exception: ./doc/confer_example.lua:1: module 'confer' not found:
	no field package.preload['confer']
	no file '/usr/local/share/lua/5.4/confer.lua'
	no file '/usr/local/share/lua/5.4/confer/init.lua'
	no file '/usr/local/lib/lua/5.4/confer.lua'
	no file '/usr/local/lib/lua/5.4/confer/init.lua'
	no file './confer.lua'
	no file './confer/init.lua'
	no file '/usr/local/lib/lua/5.4/confer.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './confer.so'
```

So obviously calling `dofile` on the runtime `confer.lua` file that I have on disk doesn't quite do what I want it to do.

Is there a pattern you'd recommend to make the Lua module `confer` available for the next script? I imagine I could produce this module from within HsLua but the only problem is that I aim to be friendly with LuaLS and LSP, and I'm not sure I can achieve such a thing with documented modules.

**Comment by tarleb** [comment]
I would probably use [file-embed](https://hackage.haskell.org/package/file-embed) or something similar.

Making documented modules easier to use with LSP has been on my todo-list for a while. It would be doable with a bit of plain Lua hacking. I can look into that over the next few days.

**Comment by tchoutri** [comment]
Got it, thanks!
