### ISSUE TITLE
big-endian builds of 0.9.5.1 fail 17 tests

### ISSUE THREAD

**Issue by clinty** [hslua/hslua#64]
```
    setting and getting a global works:                           FAIL
      test/Test/HsLua/Util.hs:35:
      lua operation returned false
```

and 16 others.

https://buildd.debian.org/status/fetch.php?pkg=haskell-hslua&arch=mips&ver=0.9.5.1-3&stamp=1524239937&raw=0

**Comment by tarleb** [comment]
I'm terribly sorry, this issue got lost. There have been large-scale rewrites since 0.9.5.1, hopefully the issue has been fixed along the way. Closing now, please reopen if the issue persists with the latest version.
