### ISSUE TITLE
Use Generics to derive push/pull functions for Haskell data types

### ISSUE THREAD

**Issue by tarleb** [hslua/hslua#69]

**Comment by luc-tielen** [comment]
I did something similar for serializing values back and forth between Haskell and Souffle in my [souffle-haskell](https://github.com/luc-tielen/souffle-haskell) library.
I have to mention that I limited it (via compile time checks) only to product types, but it gives you an idea how to approach it.
Here are some of the most important parts:

- https://github.com/luc-tielen/souffle-haskell/blob/master/lib/Language/Souffle/Marshal.hs#L126-L148
- https://github.com/luc-tielen/souffle-haskell/blob/master/lib/Language/Souffle/Marshal.hs#L126-L148

For Lua you can do something similar probably.. if you want to support sum-types as well, you will probably need to keep track of a "tag" somewhere. 

If you need more information, let me know. :)

**Comment by tarleb** [comment]
That's awesome, thanks!

**Comment by tarleb** [comment]
I've added hslua-aeson and functions `pushViaJSON` and `peekViaJSON`. This allows to do things like

```haskell
instance Pushable Foo where
  push = pushViaJSON
```

or even 

``` haskell
instance ToJSON a => Pushable a where
  push = pushViaJSON
```

Aeson is hard to beat in terms of customization and coverage. Only downside is that it doesn't make use of metatables, but should still be sufficient for the time being.
