### ISSUE TITLE
hslua does not cross-compile

### ISSUE THREAD

**Issue by vmchale** [hslua/hslua#73]
I'm not entirely sure why, unfortunately. It fails with the following error message:

```
cabal new-build --with-ghc arm-linux-gnueabihf-ghc --with-ghc-pkg arm-linux-gnueabihf-ghc-pkg 
Build profile: -w ghc-8.6.3 -O1
In order, the following will be built (use -v for more details):
 - hslua-1.0.1 (lib) (configuration changed)
Configuring library for hslua-1.0.1..
Preprocessing library for hslua-1.0.1..
Types.hsc: In function ‘_hsc2hs_test1’:
Types.hsc:59:12: error: ‘LUA_INTEGER’ undeclared (first use in this function)
Types.hsc:59:12: note: each undeclared identifier is reported only once for each function it appears in
Types.hsc:59:24: error: expected ‘;’ before numeric constant
compilation failed
```

Thanks for any help

**Comment by tarleb** [comment]
Huh, that's bad. I have no experience in cross-compiling, so I'm afraid I'm rather clueless. The only thing that came to mind would be to move the include directives *before* the module imports – now that I think about it, I'm actually surprised that this works for x64.

Wild guessing: Is this part of an attempt to cross-compile pandoc? If so, then we could also think about adding a flag to pandoc which should allow to disable all Lua features. I've thought about this before, as it could also help to compile pandoc with ghcjs.

**Comment by tarleb** [comment]
I've opened an issue on the pandoc tracker to discuss the possibility of a cabal flag. Please don't hesitate to raise this on haskell-cafe, any help is appreciated.

**Comment by 2i3r** [comment]
I'm don't know anything about programming in `hsc`, but I can confirm by moving the `#include "lua.h"` line in `/src/Foreign/Lua/Core/Types.hsc`(v1.0.1) to line `#55` before the `import`s , then `hslua` cross-compiles to `arm-linux-gnueabihf` without problem. 
I can do a PR if it helps and nothing is wrong with this change.
I'm also trying to cross-compile the `pandoc` :)

**Comment by tarleb** [comment]
That is great to hear! PR would be most welcome.

**Comment by tarleb** [comment]
[A new release](https://hackage.haskell.org/package/hslua-1.0.2/changelog) has been published.
