### ISSUE TITLE
Loading specific libraries with open<lib> functions seems to fail

### ISSUE THREAD

**Issue by charukiewicz** [hslua/hslua#76]
Hello. Forgive me in advance for being very inexperienced with Lua, so I might be doing something wrong here. However, I'm finding that when using `hslua`, none of the library loading functions other than `openlibs` (which loads all standard libraries) seem to do anything.

Note that for the examples below I'm using Stack `lts-13.12`, and am using the `bytestring`, and `raw-string-qq` packages in addition to `hslua-1.0.2`.

-----------

### Working example using `openlibs`

```haskell
{-# LANGUAGE QuasiQuotes #-}


import           Data.ByteString.Char8
import           Foreign.Lua           as Lua 
import           Text.RawString.QQ

main :: IO ()
main = Lua.run $ do
    Lua.openlibs -- loads all Lua standard libs

    Lua.dostring luaCode

    character <- Lua.callFunc "strToUpper" "test"

    liftIO $ print (character :: String)



luaCode :: ByteString
luaCode = pack [r| 
    function strToUpper (lc_string)
        return string.upper(lc_string)
    end 
|]
```

#### OUTPUT

```
*Main> main
"TEST"
```

-----------

### Failing example using `openstring`

```haskell
{-# LANGUAGE QuasiQuotes #-}

import           Data.ByteString.Char8
import           Foreign.Lua           as Lua
import           Text.RawString.QQ

main :: IO ()
main = Lua.run $ do
    Lua.openstring -- loads only the string library

    Lua.dostring luaCode

    character <- Lua.callFunc "strToUpper" "test"

    liftIO $ print (character :: String)



luaCode :: ByteString
luaCode = pack [r|
    function strToUpper (lc_string)
        return string.upper(lc_string)
    end
|]
```

#### OUTPUT

```
*Main> main
*** Exception: Lua exception: [string "..."]:3: attempt to index a nil value (global 'string')                               
```

-----------

### Failing example using every `open<lib>` function except `openlibs`

I get the same output even if I load [all of the libraries defined in `Foreign.Lua.Core`](https://hackage.haskell.org/package/hslua-1.0.2/docs/Foreign-Lua-Core.html#g:19), e.g.

```haskell
-- .... same as previous example

main = Lua.run $ do
    Lua.openbase
    Lua.openio
    Lua.openmath
    Lua.openpackage
    Lua.openos
    Lua.openstring
    Lua.opentable

-- .... same as previous example
```

#### OUTPUT

```
*Main> main
*** Exception: Lua exception: [string "..."]:3: attempt to index a nil value (global 'string')                               
```

-----------

Is there any reason why this should be failing? Is this a bug? I'm trying to use only the String functions in Lua, and I'm following the [suggestions in the Wiki example](https://wiki.haskell.org/HsLua), which say:

> Note that fresh Lua instances only have access to a dozen standard (arithmetic) operations. By careful selection of functions provided to the Lua instance, you can turn it into sandbox - e.g. disallow access to file system, network connections and so on, or provide special functions which can access only specific directory/host/whatever.

**Comment by tarleb** [comment]
The problem is that all  `open*` functions *other than* `openlibs` only push the specified module to the stack, but don't assign a global variable. You'll probably want to do

``` haskell
Lua.openstring -- loads only the string library
Lua.setglobal "string" -- make it available using the global "string"
```

We could think about adding a binding to `luaL_requiref`, which, I believe, would solve this. I haven't done this yet, as C function pointers are not very natural to use from Haskell. There might be a better way.

**Comment by charukiewicz** [comment]
Ah, makes sense. Thank you for clarifying that @tarleb. I wasn't able to find any examples that used anything other than `openlibs` (both in the `hslua-examples` repo and via searching blog posts), so I assumed the other `open*` functions worked the same way.

Looking more closely at the Lua documentation, this behavior makes sense (`luaL_openlibs` is equivalent to `luaL_requiref`, but something like `openstring` on the HsLua side is really an argument for `luaL_requiref`).

Do you think it would be worth clarifying this distinction in the [documentation associated](https://hackage.haskell.org/package/hslua-1.0.2/docs/Foreign-Lua-Core.html#g:19) with the `open*` functions? Currently each of the `open*` functions says:

> Opens Lua's <lib_name> library into the current state.

Whereas `openlibs` says:

> Opens all standard Lua libraries into the current state.

This would suggest that the two are exactly equivalent, but they're slightly different in what they're doing.

**Comment by tarleb** [comment]
Thank you for looking into this. I agree,the current wording is very confusing. Do you have a good description that would be more clear?

**Comment by charukiewicz** [comment]
I think that some sort of indication of the distinction between the two.

Either changing `openlibs` to say:

> Opens all standard Lua libraries into the current state and sets each library name as a global value.

Or changing the others to say the inverse:

> Opens Lua's <lib_name> library into the current state. Does not set the library name into the global value.

In thinking about, I'm thinking applying the change to `openlibs` would be the better route, as the other approach is somewhat strange as far as documentation goes. It's kind of unusual for a function to say what it does *not* do. Plus the latter would require repeating this description for each of the `open<lib>` functions.

The question is whether there is a more accurate way of phrasing it than to say *"and sets each library name as a global value"*.

**Comment by tarleb** [comment]
Thanks!
