### ISSUE TITLE
Expose Internals

### ISSUE THREAD

**Issue by alexloomis** [hslua/hslua#80]
Create an `Internal` module or otherwise expose internals to make extending functionality easier. For example, to write a version of `nextPair` that uses `peekKeyValuePairs` instead of `peek` in order to correctly read a nested table.

**Comment by alexloomis** [comment]
My specific use case is adequately covered by `Foreign.Lua.Push` and `Foreign.Lua.Pull`.

**Comment by tarleb** [comment]
Foreign.Lua.{Peek,Push} are now available as of HsLua 1.1.1.
