### ISSUE TITLE
Overlapping Instances

### ISSUE THREAD

**Issue by alexloomis** [hslua/hslua#82]
Create overlapping instances for `Peekable [(a,b)]` and `Pushable [(a,b)]` so they act like a key-value map rather than lists of pairs of inputs/outputs.

**Comment by tarleb** [comment]
I'd rather not do this. Overlapping instances always have the potential to cause confusion. The current behavior is well established and consistent with aeson, which also encodes pairs as two-element JSON lists.

I'd be ok with adding a newtype for key-value-pairs taken from a single Lua table.

**Comment by alexloomis** [comment]
That makes sense. Once you're using a newtype you may as well use `Map`, the only advantage to using `[(a,b)]` directly is it conforms to my intuition of what would happen, but consistency beats that out.
