### ISSUE TITLE
Lua 5.4 support

### ISSUE THREAD

**Issue by felixonmars** [hslua/hslua#84]
Lua 5.4 has been released some time ago. Is there any plan to support the new version soon?

**Comment by tarleb** [comment]
Ultimately: yes. Short-term: no.

Lua 5.4 came out just a little over a month ago, contains a couple of
(security sensitive) bugs, and isn't in wide-spread adoption yet. It is
rather low on my priority list for that reason. I don't think I'll get
to work on this within the next few months. For now I'll just wait for
the upcoming 5.3.6.

**Comment by tarleb** [comment]
I've added a new branch lua-5.4 which adds support for Lua 5.4 and includes 5.4.2. I plan to release the refactored `lua` Haskell package as lua-2.0.0, and then do a second release of lua-3.0.0 after merging the branch. So lua-2.\* will contain Lua 5.3, and lua-3.\* will have 5.4. The hslua-core package, which provides the Haskell wrappers, will support both version.

I'll leave the issue open until the branch has been merged and the new versions are released.

**Comment by tarleb** [comment]
I finally have time to drive this forward. HsLua now works with both Lua 5.3 and 5.4, and ships with 5.4.4 by default. I will release this as hslua-2.2 within the next week or so.

My plan is to then remove support for Lua 5.3, so we can use all the new features offered by 5.4. This will take a little longer.
