### ISSUE TITLE
Crashes in pandoc's Lua subsystem

### ISSUE THREAD

**Issue by tarleb** [hslua/hslua#92]
Pandoc's test suite sometimes fails due to (what appears to be) a double-free induced crash in HsLua.

Steps to reproduce:

- In pandoc's sources, edit file `test/Tests/Lua.hs`, changing [`(QuickCheckTests 20)`](https://github.com/jgm/pandoc/blob/master/test/Tests/Lua.hs#L44) to `(QuickCheckTests 4000)`.
- Compile a pandoc binary with `cabal build`.
- Run Lua filter test-suite with `cabal test --test-option=-p"Lua filters"`. In some cases, the test will terminate with a crash. usually when testing round-tripping of Meta or Pandoc values.

The crash is not fully reproducible. On some machines, the problem appears significantly more often than on others. Crashes also appear to correlate with reduced memory availability on the system.

The issue was first noticed with hslua-1.2.0 and has been observed with hslua-1.3.0 as well, but the crash can be induced even with hslua-1.1.2. Previous versions have not been tried yet.

See also: jgm/pandoc#6674

CC: @jgm

**Comment by tarleb** [comment]
Message when crashing is either

> `double free or corruption (!prev)`

or

> `malloc(): memory corruption (fast)`

or

> `malloc(): mismatching next->prev_size (unsorted)`

**Comment by tarleb** [comment]
This can be fixed by disabling the `allow-unsafe-gc` flag; it's not *entirely* clear to me whether this is a problem with hslua or with the GHC garbage collector.

**Comment by jgm** [comment]
I'd still love to get to the bottom of this.

As a start, would it help to add to the README for this project more details on "haskell finalizers must be handled with extreme care" (an example perhaps?), and also something about how much of a speedup we get in pandoc by having the unsafe gc enabled?  If I were using the library, I'd really have no idea from the documentation whether it was safe to enable the flag, or what the benefits would be.

**Comment by tarleb** [comment]
I started to rework the library from the ground up. The `allow-unsafe-gc` flag is now documented as follows:

> Allow optimizations which make Lua's garbage collection
> potentially unsafe; enabling this should be safe if
> there are no callbacks into Haskell during Lua garbage
> collection cycles. The flag should be *disabled* if Lua
> objects can have Haskell finalizers, i.e., `__gc`
> metamethods that call Haskell function.

The rewrite will take a while. My hope is that by doing this, I'll get rid of all the ugly warts that are currently present in the library.

**Comment by jgm** [comment]
Sounds great. The new documentation is much better!

**Comment by tarleb** [comment]
Closing in favor of #98.
