### ISSUE TITLE
Loading library fails: Dynamic loading not supported

### ISSUE THREAD

**Issue by manimax3** [hslua/hslua#93]
I'm trying to run `require'luv'` inside a pandoc lua filter which fails with `Dynamic loading not supported`.
However `lua5.3 <(echo "require'luv'")` works fine.

Luv is a compiled library. Is this something that is disabled by hslua?

**Comment by tarleb** [comment]
This should work in general, but depends on the flags with which pandoc was compiled. The binaries available from the download area are all static, but you'll need a pandoc binary which wasn't built with the `export-dynamic` hslua build flag disabled.

The solution is thus to use a binary shipped with your disctirubtion -- or complain to them if you already do. Alternatively compile pandoc yourself or use a pandoc Docker image.

**Comment by manimax3** [comment]
Alright I compiled it with the right flag and it works fine now. Thanks! Will close this then.
