### ISSUE TITLE
Ignore shebang in loaded files

### ISSUE THREAD

**Issue by alerque** [hslua/hslua#99]
Using `loadFile()` should be able to load and parse a Lua source file that starts with a shebang / hashbang. Basically a treating it as a special comment syntax only valid on the first line where anything starting with `#!` is treated as a comment should be fine.

This matters downstream for Pandoc where filters might be both Pandoc filters AND stand alone system scripts.

cf. https://github.com/jgm/pandoc/issues/7555#issuecomment-922504432

**Comment by nrnrnr** [comment]
Adding myself to this issue because my Pandoc filters have been affected.

(I use a single file as a polyglot between `#!/usr/bin/env lua` and also a Pandoc filter.)
